-- AlterTable
ALTER TABLE `category` MODIFY `grossSales` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `discounts` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `netSales` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `cost` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `profit` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `markup` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `percentOfSales` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `quantity` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `month` MODIFY `grossSales` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `discounts` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `netSales` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `cost` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `profit` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `markup` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `percentOfSales` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `quantity` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `quarter` MODIFY `grossSales` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `discounts` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `netSales` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `cost` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `profit` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `markup` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `percentOfSales` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `quantity` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `subcategory` MODIFY `grossSales` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `discounts` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `netSales` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `cost` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `profit` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `markup` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `percentOfSales` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `quantity` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `year` MODIFY `grossSales` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `discounts` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `netSales` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `cost` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `profit` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `markup` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `percentOfSales` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `quantity` INTEGER NOT NULL DEFAULT 0;
